export const FETCH_OFFERS_REQUEST = "FETCH_OFFERS_REQUEST";
export const FETCH_OFFERS_SUCCESS = "FETCH_OFFERS_SUCCESS";
export const FETCH_OFFERS_FAILURE = "FETCH_OFFERS_FAILURE";

export const ADD_OFFER_REQUEST = "ADD_OFFER_REQUEST";
export const ADD_OFFER_SUCCESS = "ADD_OFFER_SUCCESS";
export const ADD_OFFER_FAILURE = "ADD_OFFER_FAILURE";
export const RESET_ADD_OFFER_STATE = "RESET_ADD_OFFER_STATE";

export const UPDATE_OFFER_REQUEST = "UPDATE_OFFER_REQUEST";
export const UPDATE_OFFER_SUCCESS = "UPDATE_OFFER_SUCCESS";
export const UPDATE_OFFER_FAILURE = "UPDATE_OFFER_FAILURE";
export const RESET_UPDATE_OFFER_STATE = "RESET_UPDATE_OFFER_STATE";

export const DELETE_OFFER_REQUEST = "DELETE_OFFER_REQUEST";
export const DELETE_OFFER_SUCCESS = "DELETE_OFFER_SUCCESS";
export const DELETE_OFFER_FAILURE = "DELETE_OFFER_FAILURE";
export const RESET_DELETE_OFFER_STATE = "RESET_DELETE_OFFER_STATE";