export const LIFESTYLE_FETCH_REQUEST = "LIFESTYLE_FETCH_REQUEST";
export const LIFESTYLE_FETCH_SUCCESS = "LIFESTYLE_FETCH_SUCCESS";
export const LIFESTYLE_FETCH_FAILURE = "LIFESTYLE_FETCH_FAILURE";

export const LIFESTYLE_ADD_REQUEST = "LIFESTYLE_ADD_REQUEST";
export const LIFESTYLE_ADD_SUCCESS = "LIFESTYLE_ADD_SUCCESS";
export const LIFESTYLE_ADD_FAILURE = "LIFESTYLE_ADD_FAILURE";
export const LIFESTYLE_ADD_RESET = "LIFESTYLE_ADD_RESET";

export const LIFESTYLE_UPDATE_REQUEST = "LIFESTYLE_UPDATE_REQUEST";
export const LIFESTYLE_UPDATE_SUCCESS = "LIFESTYLE_UPDATE_SUCCESS";
export const LIFESTYLE_UPDATE_FAILURE = "LIFESTYLE_UPDATE_FAILURE";
export const LIFESTYLE_UPDATE_RESET = "LIFESTYLE_UPDATE_RESET";

export const LIFESTYLE_DELETE_REQUEST = "LIFESTYLE_DELETE_REQUEST";
export const LIFESTYLE_DELETE_SUCCESS = "LIFESTYLE_DELETE_SUCCESS";
export const LIFESTYLE_DELETE_FAILURE = "LIFESTYLE_DELETE_FAILURE";
export const LIFESTYLE_DELETE_RESET = "LIFESTYLE_DELETE_RESET";