export const FETCH_COINS_REQUEST = "FETCH_COINS_REQUEST";
export const FETCH_COINS_SUCCESS = "FETCH_COINS_SUCCESS";
export const FETCH_COINS_FAILURE = "FETCH_COINS_FAILURE";

export const ADD_COINS_REQUEST = "ADD_COINS_REQUEST";
export const ADD_COINS_SUCCESS = "ADD_COINS_SUCCESS";
export const ADD_COINS_FAILURE = "ADD_COINS_FAILURE";

export const DELETE_COINS_REQUEST = "DELETE_COINS_REQUEST";
export const DELETE_COINS_SUCCESS = "DELETE_COINS_SUCCESS";
export const DELETE_COINS_FAILURE = "DELETE_COINS_FAILURE";

export const UPDATE_COINS_REQUEST = "UPDATE_COINS_REQUEST";
export const UPDATE_COINS_SUCCESS = "UPDATE_COINS_SUCCESS";
export const UPDATE_COINS_FAILURE = "UPDATE_COINS_FAILURE";

export const RESET_UPDATE_COINS_STATE = "RESET_UPDATE_COINS_STATE";