// src/features/CallsHistory/CallsHistoryType.js

export const FETCH_CALLS_HISTORY_REQUEST = "FETCH_CALLS_HISTORY_REQUEST";
export const FETCH_CALLS_HISTORY_SUCCESS = "FETCH_CALLS_HISTORY_SUCCESS";
export const FETCH_CALLS_HISTORY_FAILURE = "FETCH_CALLS_HISTORY_FAILURE";