export const FETCH_LIFESTYLECATEGORY_REQUEST = "FETCH_LIFESTYLECATEGORY_REQUEST";
export const FETCH_LIFESTYLECATEGORY_SUCCESS = "FETCH_LIFESTYLECATEGORY_SUCCESS";
export const FETCH_LIFESTYLECATEGORY_FAILURE = "FETCH_LIFESTYLECATEGORY_FAILURE";

export const ADD_LIFESTYLECATEGORY_REQUEST = "ADD_LIFESTYLECATEGORY_REQUEST";
export const ADD_LIFESTYLECATEGORY_SUCCESS = "ADD_LIFESTYLECATEGORY_SUCCESS";
export const ADD_LIFESTYLECATEGORY_FAILURE = "ADD_LIFESTYLECATEGORY_FAILURE";

export const UPDATE_LIFESTYLECATEGORY_REQUEST = "UPDATE_LIFESTYLECATEGORY_REQUEST";
export const UPDATE_LIFESTYLECATEGORY_SUCCESS = "UPDATE_LIFESTYLECATEGORY_SUCCESS";
export const UPDATE_LIFESTYLECATEGORY_FAILURE = "UPDATE_LIFESTYLECATEGORY_FAILURE";

export const DELETE_LIFESTYLECATEGORY_REQUEST = "DELETE_LIFESTYLECATEGORY_REQUEST";
export const DELETE_LIFESTYLECATEGORY_SUCCESS = "DELETE_LIFESTYLECATEGORY_SUCCESS";
export const DELETE_LIFESTYLECATEGORY_FAILURE = "DELETE_LIFESTYLECATEGORY_FAILURE";