export const FETCH_USER_REQUEST="FETCH_USER_REQUEST"
export const FETCH_USER_SUCCESS="FETCH_USER_SUCCESS"
export const FETCH_USER_FAILURE="FETCH_USER_FAILURE"

export const EDIT_USER_REQUEST="EDIT_USER_REQUEST"
export const EDIT_USER_SUCCESS="EDIT_USER_SUCCESS"
export const EDIT_USER_FAILURE="EDIT_USER_FAILURE"