export const FETCH_INTEREST_REQUEST = "FETCH_INTEREST_REQUEST";
export const FETCH_INTEREST_SUCCESS = "FETCH_INTEREST_SUCCESS";
export const FETCH_INTEREST_FAILURE = "FETCH_INTEREST_FAILURE";

export const ADD_INTEREST_REQUEST = "ADD_INTEREST_REQUEST";
export const ADD_INTEREST_SUCCESS = "ADD_INTEREST_SUCCESS";
export const ADD_INTEREST_FAILURE = "ADD_INTEREST_FAILURE";
export const RESET_ADD_INTEREST_STATE = "RESET_ADD_INTEREST_STATE";

export const EDIT_INTEREST_REQUEST = "EDIT_INTEREST_REQUEST";
export const EDIT_INTEREST_SUCCESS = "EDIT_INTEREST_SUCCESS";
export const EDIT_INTEREST_FAILURE = "EDIT_INTEREST_FAILURE";
export const RESET_EDIT_INTEREST_STATE = "RESET_EDIT_INTEREST_STATE";

export const DELETE_INTEREST_REQUEST = "DELETE_INTEREST_REQUEST";
export const DELETE_INTEREST_SUCCESS = "DELETE_INTEREST_SUCCESS";
export const DELETE_INTEREST_FAILURE = "DELETE_INTEREST_FAILURE";
export const RESET_DELETE_INTEREST_STATE = "RESET_DELETE_INTEREST_STATE";